name: PowerShell Task

on:
  workflow_call:
    inputs:
      SourcePath:
        required: true
        type: string
      MachineNames:
        required: true
        type: string
      AdminUserName:
        required: true
        type: string
      AdminPassword:
        required: true
        type: string
      TargetPath:
        required: true
        type: string
      CleanTarget:
        required: false
        type: boolean
      CopyFilesInParallel:
        required: false
        type: boolean

jobs:
  execute-powershell:
    runs-on: self-hosted
    steps:
      - name: Execute PowerShell Script
        run: |
          try {
              # Assign inputs to variables
              $sourcePath = "${{ inputs.SourcePath }}"
              $machines = "${{ inputs.MachineNames }}"
              $username = "${{ inputs.AdminUserName }}"
              $password = "${{ inputs.AdminPassword }}"
              $targetPath = "${{ inputs.TargetPath }}"
              $cleanTarget = ${{ inputs.CleanTarget }}
              $copyFilesInParallel = ${{ inputs.CopyFilesInParallel }}

              # Convert password to secure string and create a credential object
              $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
              $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)

              # Map the network share
              Write-Host "Mapping network share: $targetPath"
              net use $targetPath /user:$username $password

              # Clean target if requested
              if ($cleanTarget) {
                  Write-Host "Cleaning target path: $targetPath"
                  Remove-Item -Path $targetPath\* -Recurse -Force
              }

              # Copy files using robocopy
              if ($copyFilesInParallel) {
                  Write-Host "Copying files in parallel from $sourcePath to $targetPath"
                  Start-Job -ScriptBlock {
                      robocopy $using:sourcePath $using:targetPath /MIR /Z /R:3 /W:5
                  } | Wait-Job
              } else {
                  Write-Host "Copying files sequentially from $sourcePath to $targetPath"
                  robocopy $sourcePath $targetPath /MIR /Z /R:3 /W:5
              }

              # Unmap the network share
              Write-Host "Unmapping network share: $targetPath"
              net use $targetPath /delete
          } catch {
              Write-Error "An error occurred: $_"
              exit 1
          }
