name: PowerShell Task

on:
  workflow_call:
    inputs:
      SourcePath:
        required: true
        type: string
      MachineNames:
        required: true
        type: string
      AdminUserName:
        required: true
        type: string
      AdminPassword:
        required: true
        type: string
      TargetPath:
        required: true
        type: string
      CleanTarget:
        required: false
        type: boolean
      CopyFilesInParallel:
        required: false
        type: boolean

jobs:
  execute-powershell:
    runs-on: self-hosted

    steps:
      - name: Execute PowerShell Script
        shell: pwsh
        run: |
          try {
              $sourcePath = "${{ inputs.SourcePath }}"
              $machines = "${{ inputs.MachineNames }}"
              $username = "${{ inputs.AdminUserName }}"
              $password = "${{ inputs.AdminPassword }}"
              $targetPath = "${{ inputs.TargetPath }}"
              $cleanTarget = ${{ inputs.CleanTarget }}
              $copyFilesInParallel = ${{ inputs.CopyFilesInParallel }}

              # Secure credentials
              $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
              $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)

              Write-Host "Mapping network share: $targetPath"
              net use $targetPath /user:$username $password

              # Build robocopy options
              $robocopyOptions = "/MIR /Z /R:3 /W:5"
              if ($copyFilesInParallel) {
                  $robocopyOptions += " /MT:8"
              }
              if ($cleanTarget) {
                  $robocopyOptions += " /PURGE"
              }

              Write-Host "Running Robocopy with options: $robocopyOptions"
              robocopy $sourcePath $targetPath $robocopyOptions

              Write-Host "Unmapping network share: $targetPath"
              net use $targetPath /delete
          } catch {
              Write-Error "An error occurred: $_"
              exit 1
          }
